#
# prgm/start/Makefile
#

-include ../../estab.mk
include $(BLDD)/local.mk

TARGET := test
ENV    := prgm
CSRCS  := test.c
LIBS   := cstd frosk
LOCAL_CFLAGS :=

include $(BLDD)/template.mk
include $(BLDD)/rules.mk
