#
# util/fsb/Makefile
#

-include ../../estab.mk
include $(TOPD)/local.mk

TARGET := fsb
ENV    := util
CSRCS  := main.c fs.c parse.c directive.c
LOCAL_CCFLAGS := -g

include $(TOPD)/template.mk
include $(TOPD)/rules.mk
