#
# util/fsb/Makefile
#

-include ../../estab.mk
include $(BLDD)/local.mk

TARGET := fsb
ENV    := util
CSRCS  := main.c fs.c parse.c directive.c
LOCAL_CCFLAGS := -g

include $(BLDD)/template.mk
include $(BLDD)/rules.mk
