#
# prgm/start/Makefile
#

-include ../../estab.mk
include $(BLDD)/local.mk

TARGET := start
ENV    := prgm
CSRCS  := start.c fcurses.c
LIBS   := frosk cstd
LOCAL_CFLAGS :=

include $(BLDD)/template.mk
include $(BLDD)/rules.mk
